import React from 'react';



function Commission() {
  
    return (


        <div className="commissionContainer">

            <h1 className="commissionHeader">Artist tools</h1>

            <p className="commissionText">
                With creation AI(Artificial Intelligence) tools it is important to know how the artwork was created since creating 
                arworks with AI tools  like Midjourney, Stable Diffusion can cause a lot of legal trouble in the future depending on the use
                of the commisioned art. The current AI image tools are built on unethically on lots of copyrighted material without compensating
                the artists whose artworks were used in training the AI tools. 

            </p>
<br/>
            <p className="commissionText">
                I do not and refuse to use AI since the tool was created on stolen artworks as mentioned before. 
                It is also important to mention that a lot of artist are also losing potential revenue and oppurtunities to support themselves.
                Overal AI tools are not only exploit artist but also are being used against them so using the current AI doeent sit well with me.

                There are also many other reasons why not to use AI tools such as having no control over the image that was generated by the AI which makes siginificant changes later a lot harder. 
                
                The software I am using is Krita.
            </p>


            <h1 className="commissionHeader">Process</h1>

            <p className="commissionText">
            When commisioning any artist provide a 
            brief description of the commission, 
            the purpose of the artowrk,
            
            
            </p>


            <h1 className="commissionHeader">Copyrights/Rights/Usage</h1>

            
            <p className="commissionText">
            Commisiobed art is 


            When commisioning any artist provide a 
            brief description of the commission, 
            the purpose of the artowrk,
            
            
            </p>

            <h1 className="commissionHeader">Copyrights/Rights</h1>


            <p className="commissionText"></p>
            

        </div>







    )
}
export default Commission;
