name: Test environment
on: 
  push:
    branches:
      - testEnvironment

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          cd /var/www/html/testEnv/artWebsite
          git stash
          git pull origin testEnvironment
          composer update					
          npm install
          npm run production
          chown -R www-data:www-data /var/www/html/testEnv/artWebsite
          php artisan optimize
